#!/bin/bash
sudo dnf update -y
flatpak update -y
~/bin/commit.sh

# Rebuild obs
cd ${HOME}/Projects/local/obs/obs-studio
git pull
cd ${HOME}/Projects/local/obs/obs-studio/build
cmake ..
make -j8
sudo make install

sudo shutdown now
