#!/bin/bash
oc adm drain node5.ocp.khary.net --ignore-daemonsets --delete-emptydir-data --kubeconfig=${HOME}/kubeconfig-noingress --grace-period=0 --force
oc adm uncordon node5.ocp.khary.net --kubeconfig=${HOME}/kubeconfig-noingress

sudo virsh shutdown ocp-node-5


sudo dnf update -y
flatpak update -y
sudo snap refresh
~/bin/commit.sh

# Rebuild obs
# https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux
${HOME}/bin/build_obs.sh

while [ "$(sudo virsh domstate ocp-node-5)" != "shut off" ]; do
    echo "Waiting for VM to shut down..."
    sleep 1  # Sleep for 1 second before checking again
done
echo "VM is now shut off."

sudo shutdown now
