#!/bin/bash
sudo dnf update -y
flatpak update -y
~/bin/commit.sh

# Rebuild obs
cd ${HOME}/Projects/local/obs/obs-studio
git pull
git submodule update
cd ${HOME}/Projects/local/obs/obs-studio/build
cmake -DENABLE_BROWSER=ON -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DCEF_ROOT_DIR="../../cef_binary_4638_linux64" -DENABLE_AJA=OFF .. 
make -j$(nproc)
sudo make install

oc adm drain node4.ocp.khary.net --ignore-daemonsets --kubeconfig=~/kubeconfig-noingress

sudo shutdown now
